name: (Optional) Detect Breaking Changes
on: 
  pull_request: 
     ## Exclude major releases containing breaking changes info
     paths-ignore: 
      - 'tools/releaser/breaking_changes/**'
jobs:
  go-apidiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - uses: joelanford/go-apidiff@main
    - name: braking change detected
      if: ${{ failure() }}
      run: echo "run `Review job for false positives. If you see any issues run `make update-version` and commit the changes."
